import type ITimestamps from "../Timestamps";
import type IArticle from "./Article";
import type ICategory from "./Category";
import type ICity from "./City";
import type IClinicCategory from "./ClinicCategory";
import type IClinicPhone from "./ClinicPhone";
import type IClinicService from "./ClinicService";
import type IClinicWorkTime from "./ClinicWorkTime";
import type IFavorite from "./Favorite";
import type IImage from "./Image";
import type IImageRelat from "./ImageRelat";
import type IReview from "./Review";

export default interface IClinic extends ITimestamps {
  id: number;
  name: string;
  address: string;
  rating: number;
  link: string;
  link_name: string;
  longitude: number;
  latitude: number;
  description?: string;
  is_verification: boolean;
  owner_id: number;
  icon_id?: number;
  link_vk?: string;
  link_videohost?: string;
  main_category: ICategory;
  clinic_categories?: IClinicCategory[];
  clinic_services?: IClinicService[];
  city?: ICity;
  clinic_phones?: IClinicPhone[];
  icon?: IImage;
  images?: IImageRelat[];
  work_times: IClinicWorkTime[];
  reviews?: IReview[];
  articles?: IArticle[];
  my_favorite?: IFavorite;
  my_review?: IReview;
}
