export const ROUTES_NAMES = {
  cities: "/cities",
  clinic: "/clinic",
  profile: "/profile",
  profile_edit: "/profile/edit",
  profile_favorites: "/profile/favorites",
  profile_appointment_future: "/profile/appointment/future",
  profile_appointment_past: "/profile/appointment/past",
  clinic_profile: "/clinic-profile",
  clinic_profile_clinics: "/clinic-profile/clinics",
  clinic_profile_clinics_id: (id: number) => `/clinic-profile/clinics/${id}`,
  about: "/about",
  main: "/",
  login: "/login",
  offer: "/offer",
  policy: "/policy",
  regions: "/regions",
  register: "/register",
};
